#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


PROMPT_DIR = Path(__file__).resolve().parent.parent / "prompts"


def discover_prompt_files(prompt_dir: Path | None = None) -> list[Path]:
    root = prompt_dir or PROMPT_DIR
    return sorted(
        path for path in root.iterdir()
        if path.is_file() and path.suffix.lower() == ".md" and not path.name.endswith("-implementation.md")
    )


def find_implementation_prompt(prompt_path: Path) -> Path:
    implementation_path = prompt_path.with_name(f"{prompt_path.stem}-implementation.md")
    if not implementation_path.exists():
        raise FileNotFoundError(f"No implementation prompt found for {prompt_path.name}")
    return implementation_path


def parse_implementation_prompt(implementation_path: Path) -> dict[str, str]:
    text = implementation_path.read_text(encoding="utf-8")
    matches = re.findall(r"^##\s+(.+?)\n```(?:\w+)?\n(.*?)\n```", text, re.MULTILINE | re.DOTALL)

    if not matches:
        raise ValueError(f"Implementation prompt {implementation_path.name} does not contain file sections.")

    files: dict[str, str] = {}
    for file_name, contents in matches:
        files[file_name.strip()] = contents.strip() + "\n"
    return files


def add_runtime_manifest(generated_files: dict[str, str]) -> None:
    has_python = any(name.endswith(".py") for name in generated_files)
    has_node = any(name.endswith((".js", ".ts", ".mjs", ".cjs")) for name in generated_files)

    if has_python and "requirements.txt" not in generated_files:
        generated_files["requirements.txt"] = "# Generated by regen toolchain\n"

    if has_node and "package.json" not in generated_files:
        generated_files["package.json"] = json.dumps(
            {
                "name": "generated-app",
                "private": True,
                "scripts": {"start": "node app.js"},
                "dependencies": {},
            },
            indent=2,
        ) + "\n"


def generate_app(prompt_path: Path, output_dir: Path) -> Path:
    implementation_prompt = find_implementation_prompt(prompt_path)
    generated_files = parse_implementation_prompt(implementation_prompt)
    add_runtime_manifest(generated_files)

    output_dir.mkdir(parents=True, exist_ok=True)
    for relative_name, contents in generated_files.items():
        target = output_dir / relative_name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents, encoding="utf-8")

    summary = f"# Generated app from {prompt_path.stem}\n\nPrompt: {prompt_path.name}\n\nThis output was generated from the matching implementation prompt and is not kept in source control.\n"
    (output_dir / "README.md").write_text(summary, encoding="utf-8")
    return output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="Discover and generate code from prompt files.")
    parser.add_argument("prompt", type=Path, nargs="?", help="Optional prompt file to generate from.")
    parser.add_argument("--prompt-dir", type=Path, default=PROMPT_DIR, help="Directory containing prompt files.")
    parser.add_argument("--output", type=Path, default=Path("generated"), help="Directory to write generated files to.")
    args = parser.parse_args()

    prompt_dir = args.prompt_dir
    if not prompt_dir.exists():
        raise FileNotFoundError(f"Prompt directory not found: {prompt_dir}")

    discovered = discover_prompt_files(prompt_dir)
    if not discovered:
        raise FileNotFoundError(f"No prompt files found in {prompt_dir}")

    selected_prompt = args.prompt
    if selected_prompt is None:
        if len(discovered) == 1:
            selected_prompt = discovered[0]
        else:
            names = ", ".join(p.name for p in discovered)
            raise SystemExit(f"Multiple prompts found: {names}. Choose one explicitly.")

    if not selected_prompt.exists():
        selected_prompt = prompt_dir / selected_prompt.name if not selected_prompt.is_absolute() else selected_prompt

    if not selected_prompt.exists():
        raise FileNotFoundError(f"Prompt not found: {selected_prompt}")

    target = generate_app(selected_prompt, args.output)
    print(f"Generated app from {selected_prompt.name} into {target}")
    print(f"Available prompts: {', '.join(p.name for p in discovered)}")


if __name__ == "__main__":
    main()
